
import config.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Categorias extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    
    public Categorias() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtbnRegrInicio = new javax.swing.JButton();
        jbtnBebidas = new javax.swing.JButton();
        jbtnParrillas = new javax.swing.JButton();
        jbtnPastas = new javax.swing.JButton();
        jbtnPeruanitos = new javax.swing.JButton();
        jbtnPollos = new javax.swing.JButton();
        jbtnPizzas = new javax.swing.JButton();
        jtbnPiqueos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CATEGORÍAS ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, 30));

        jtbnRegrInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jtbnRegrInicio.setText("INICIO");
        jtbnRegrInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnRegrInicioActionPerformed(evt);
            }
        });
        jPanel1.add(jtbnRegrInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 120, 40));

        jbtnBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebida.png"))); // NOI18N
        jbtnBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBebidasActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 50));

        jbtnParrillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/parrilla.png"))); // NOI18N
        jbtnParrillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnParrillasActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnParrillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, 40));

        jbtnPastas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pasta.png"))); // NOI18N
        jbtnPastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPastasActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPastas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 200, 40));

        jbtnPeruanitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/peruani.png"))); // NOI18N
        jbtnPeruanitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPeruanitosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPeruanitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 40));

        jbtnPollos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pollo.png"))); // NOI18N
        jbtnPollos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPollosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPollos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, 40));

        jbtnPizzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pizza.png"))); // NOI18N
        jbtnPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPizzasActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPizzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 180, 40));

        jtbnPiqueos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piqueos.png"))); // NOI18N
        jtbnPiqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnPiqueosActionPerformed(evt);
            }
        });
        jPanel1.add(jtbnPiqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cap1.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbnRegrInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnRegrInicioActionPerformed
        String sql="delete from registro_venta";
   String sql2="delete from cliente";
        try {
            cn=con.getConnection();
            st=cn.createStatement();
            st.executeUpdate(sql);
                st.executeUpdate(sql2);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "no se borro");
        }
        JOptionPane.showMessageDialog(null,"Su compra a sido cancelada");
        
        INICIO inicio= new INICIO();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jtbnRegrInicioActionPerformed

    private void jbtnParrillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnParrillasActionPerformed
        // TODO add your handling code here:
        Parrillas newframe = new Parrillas();
         newframe.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jbtnParrillasActionPerformed

    private void jbtnPollosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPollosActionPerformed
        // TODO add your handling code here:
        Pollos newframe = new Pollos();
         newframe.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jbtnPollosActionPerformed

    private void jbtnPastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPastasActionPerformed
        // TODO add your handling code here:
        Pastas newframe = new Pastas();
         newframe.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jbtnPastasActionPerformed

    private void jbtnBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBebidasActionPerformed
        // TODO add your handling code here:
        Bebidas newframe = new Bebidas();
         newframe.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jbtnBebidasActionPerformed

    private void jbtnPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPizzasActionPerformed
        // TODO add your handling code here:
        Pizzas newframe = new Pizzas();
         newframe.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jbtnPizzasActionPerformed

    private void jbtnPeruanitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPeruanitosActionPerformed
        // TODO add your handling code here:
        Peruanitos newframe = new Peruanitos();
         newframe.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jbtnPeruanitosActionPerformed

    private void jtbnPiqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnPiqueosActionPerformed
        // TODO add your handling code here:
        Piqueos newframe = new Piqueos();
         newframe.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jtbnPiqueosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnBebidas;
    private javax.swing.JButton jbtnParrillas;
    private javax.swing.JButton jbtnPastas;
    private javax.swing.JButton jbtnPeruanitos;
    private javax.swing.JButton jbtnPizzas;
    private javax.swing.JButton jbtnPollos;
    private javax.swing.JButton jtbnPiqueos;
    private javax.swing.JButton jtbnRegrInicio;
    // End of variables declaration//GEN-END:variables
}
