
import Clases.Venta;
import config.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Pastas extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    
    String productos[]= {"Ravioles","Lasagna","Poker de pastas","FetuccinisTitanic"};

    double precios[]={29.9, 33.9, 35.9, 58.9};
    double precio=0;
    int cantidad=0;
    double ab=0;
    
    
    public Pastas() {
        initComponents();
        this.setLocationRelativeTo(null);
        Image logo=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/carrito.png"));
        btnCarrito.setIcon(new ImageIcon(logo.getScaledInstance(btnCarrito.getWidth(), btnCarrito.getHeight(), Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnCarrito = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxPastas = new javax.swing.JComboBox<>();
        spnCantidad = new javax.swing.JSpinner();
        lbimporte = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtnRegispastas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("S/. 29.90");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 70, 30));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("S/. 33.90");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 70, 30));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("S/. 35.90");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel11.setOpaque(true);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 70, 30));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("S/. 58.90");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel12.setOpaque(true);
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 70, 30));

        jButton7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton7.setText("S");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 50, 30));

        jButton5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton5.setText("C");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        btnCarrito.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnCarrito.setText("Carrito");
        btnCarrito.setActionCommand("Finalizar\ncompra");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 60, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePta/1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 140, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePta/2.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 150, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePta/3.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 150, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePta/4.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        cbxPastas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ravioles", "Lasagna", "Poker de pastas", "Fetuccinis" }));
        cbxPastas.setBorder(javax.swing.BorderFactory.createTitledBorder("Platillos"));
        cbxPastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPastasActionPerformed(evt);
            }
        });
        jPanel2.add(cbxPastas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 180, 70));

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 21, 1));
        spnCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCantidadStateChanged(evt);
            }
        });
        jPanel2.add(spnCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 80, 70));

        lbimporte.setBackground(new java.awt.Color(255, 255, 51));
        lbimporte.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbimporte.setForeground(new java.awt.Color(255, 255, 255));
        lbimporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Importe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.add(lbimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 120, 70));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PASTAS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jbtnRegispastas.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jbtnRegispastas.setText("Registrar");
        jbtnRegispastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegispastasActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnRegispastas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cap2.jpeg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegispastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegispastasActionPerformed
        
        try {
            Agregar();
            JOptionPane.showMessageDialog(null,"SE REGISTRÓ");
        } catch (Exception e) {

        }
        
    }//GEN-LAST:event_jbtnRegispastasActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        Recibo close = new Recibo();
         close.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Categorias registros = new Categorias();
        this.setVisible(false);
        registros.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cbxPastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPastasActionPerformed
        calcularPrecio();
    }//GEN-LAST:event_cbxPastasActionPerformed

    private void spnCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCantidadStateChanged
        calcularPrecio();
    }//GEN-LAST:event_spnCantidadStateChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        Recibo rec= new Recibo();
        rec.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton7ActionPerformed

    void calcularPrecio(){
        precio = precios[cbxPastas.getSelectedIndex()];
        cantidad= Integer.parseInt(spnCantidad.getValue().toString());
        ab=precio*cantidad;
        lbimporte.setText(aMoneda(ab));
    }
    
    public String aMoneda(double precio){
        return "S/."+ (precio*100.00)/100.00;
    }
    
    void Agregar(){
        String pastas=cbxPastas.getSelectedItem().toString();
        int cantidad=Integer.parseInt(spnCantidad.getValue().toString());
        double importe= ab;
            String sql="INSERT INTO registro_venta VALUES ('"+pastas+"' , "+cantidad+" ,"+importe+")";
            
            try {
                cn=con.getConnection();
                st=cn.createStatement();
                st.executeUpdate(sql);
            } catch (Exception e) {
            
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pastas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pastas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JComboBox<String> cbxPastas;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnRegispastas;
    private javax.swing.JLabel lbimporte;
    private javax.swing.JSpinner spnCantidad;
    // End of variables declaration//GEN-END:variables
}
