
import config.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LUIS
 */
public class RESUMEN extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    
    public RESUMEN() {
        initComponents();
        this.setLocationRelativeTo(null); 
        listarResumenCliente();
        listarResumen();
        listarTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaR = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 0, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESUMEN DE COMPRA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        btnFinalizar.setText("FINALIZAR");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 150, 70));

        txaR.setEditable(false);
        txaR.setColumns(20);
        txaR.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txaR.setLineWrap(true);
        txaR.setRows(5);
        txaR.setWrapStyleWord(true);
        txaR.setAlignmentX(6.0F);
        txaR.setAlignmentY(3.0F);
        txaR.setOpaque(false);
        jScrollPane1.setViewportView(txaR);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 270, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cap1.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
       
   String sql="delete from registro_venta";
   String sql2="delete from cliente";
        try {
            cn=con.getConnection();
            st=cn.createStatement();
            st.executeUpdate(sql);
                st.executeUpdate(sql2);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "no se borro");
        }
         JOptionPane.showMessageDialog(null, "Gracias por su compra");
        INICIO inicio= new INICIO();
        inicio.setVisible(true);
        this.dispose();
         
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RESUMEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RESUMEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RESUMEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RESUMEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RESUMEN().setVisible(true);
            }
        });
    }

    
    void listarResumenCliente(){
        String sql="select * from cliente";
        try {
            cn=con.getConnection();
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            
            while(rs.next()){
                String  nombre= rs.getString(1);
                String  apellido= rs.getString(2);
                int dni = rs.getInt(3);
                
                txaR.append("Nombre   :    " + nombre+"\n");
                txaR.append("Apellido   :    "+apellido+"\n");
                txaR.append("DNI        :    "+dni+"\n");
                txaR.append("\n");
                }
            } catch (Exception e) {
            }
    }
    
    void listarResumen(){
        String sql="select * from registro_venta";
        try {
            cn=con.getConnection();
            st=cn.createStatement();
            rs=st.executeQuery(sql);
           
            while(rs.next()){
                String  nombre= rs.getString(1);
                txaR.append(nombre+"       "+"\n");
    }
        } catch (Exception e) {
        }
    }
    
    
  
    void listarTotal(){
        String sql="select sum(importe) from registro_venta";
        try {
            cn=con.getConnection();
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            
            while(rs.next()){
                double  total= rs.getDouble(1);
                
                txaR.append("\n");
                txaR.append("Total   :    " + total+"\n");
                }
            } catch (Exception e) {
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaR;
    // End of variables declaration//GEN-END:variables
}
